name: test

on:
  pull_request:
  push:
    branches: [main]
  workflow_call:
  workflow_dispatch:

concurrency:
  group: test-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

permissions: {}

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41
        with:
          enable-cache: true

      - id: set-matrix
        run: |
          uv run nox --session "gha_matrix"

  test:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    needs: generate-matrix
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Cache nox environments and Python installations
        uses: actions/cache@v4
        with:
          path: |
            .nox
            .uv-python
          key: nox-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('uv.lock', 'noxfile.py') }}

      - name: Install uv
        uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41
        with:
          enable-cache: true
        env:
          UV_PYTHON_INSTALL_DIR: .uv-python

      - name: Install system dependencies for lxml (free-threading builds)
        if: ${{ contains(matrix.python-version, 't') }}
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libxml2-dev libxslt-dev

      - name: Run tests
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
          UV_PYTHON_INSTALL_DIR: .uv-python
        run: |
          uv run nox --session "tests(python='${PYTHON_VERSION}')"

  tests:
    runs-on: ubuntu-latest
    needs: test
    if: always()
    steps:
      - name: OK
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Fail
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1

  types:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41
        with:
          enable-cache: true

      - name: Run type checks
        run: |
          uv run nox --session "types"

  coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41
        with:
          enable-cache: true

      - name: Generate code coverage
        run: |
          uv run nox --session "coverage"
